use_frameworks!

target 'RxCocoa-Texture_Example' do
  pod 'RxCocoa-Texture', :path => '../'
  pod 'RxAlamofire'

  target 'RxCocoa-Texture_Tests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'Quick'
    pod 'Nimble'
  end
end
